Kitex:
  Service: "user_service"
  Address: "0.0.0.0:8888"
  LogLevel: info
  LogFileName: "log/kitex.log"
  LogMaxSize: 10
  LogMaxAge: 3
  LogMaxBackups: 50

Redis:
  Address: "127.0.0.1:6379"
  Username: ""
  Password: ""
  DB: 0

Registry:
  RegistryAddress:
  - 127.0.0.1:2379
  Username: ""
  Password: ""

PostgresSQL:
  Host: 127.0.0.1
  User: postgres
  Password: postgres
  Dbname: postgres
  Port: 5432
  Sslmode: disable