// Code generated by Kitex v0.12.3. DO NOT EDIT.

package userservice

import (
	"context"
	user_service "github.com/ITu-CloudWeGo/itu_rpc_user/kitex_gen/user_service"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Sign(ctx context.Context, Req *user_service.SignRequest, callOptions ...callopt.Option) (r *user_service.SignResponse, err error)
	Login(ctx context.Context, Req *user_service.LoginRequest, callOptions ...callopt.Option) (r *user_service.LoginResponse, err error)
	GetUser(ctx context.Context, Req *user_service.GetUserRequest, callOptions ...callopt.Option) (r *user_service.GetUserResponse, err error)
	UpdateUser(ctx context.Context, Req *user_service.UpdateUserRequest, callOptions ...callopt.Option) (r *user_service.UpdateUserResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Sign(ctx context.Context, Req *user_service.SignRequest, callOptions ...callopt.Option) (r *user_service.SignResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Sign(ctx, Req)
}

func (p *kUserServiceClient) Login(ctx context.Context, Req *user_service.LoginRequest, callOptions ...callopt.Option) (r *user_service.LoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, Req)
}

func (p *kUserServiceClient) GetUser(ctx context.Context, Req *user_service.GetUserRequest, callOptions ...callopt.Option) (r *user_service.GetUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUser(ctx, Req)
}

func (p *kUserServiceClient) UpdateUser(ctx context.Context, Req *user_service.UpdateUserRequest, callOptions ...callopt.Option) (r *user_service.UpdateUserResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUser(ctx, Req)
}
